import Footer from '@/sections/Footer'
import Header from '@/sections/Header'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <h1>Next.JS with Tailwind Setup</h1>
        <Footer />
      </main>
    </div>
  )
}

export default Home
